[tool.poetry]
name = "schooltools"
version = "0.1.0"
description = ""
authors = ["Nicolò Sala <nicolo.sala@protonmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11"
more-itertools = ">=9.0.0"
beautifulsoup4 = ">=4.11.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
