[tool.poetry]
name = "schooltools"
version = "0.1.0"
description = ""
authors = ["Nicolò Sala <nicolo.sala@protonmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
more-itertools = "^9.0.0"
bs4 = "^0.0.1"


[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
